### ISSUE TITLE
"Metrics collected by IBM Cloud™ Virtual Servers" link is inaccurate

### ISSUE THREAD

**Issue by jp-pollard** [ibm-cloud-docs/Monitoring-with-Sysdig#15]
Under this section: https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-cloud_services#infrastructure

The metrics link is `Metrics collected by IBM Cloud™ Virtual Servers` send the user to an empty page with `IBM Cloud Docs
Virtual Servers for Classic` breadcrumbs. Not the expected functionality. 

We would also like this to not just show `classic` virtual servers. Needs to show both `classic` and `for VPC`. 

See screenshots below: 

<img width="1863" alt="Screen Shot 2020-09-23 at 8 46 43 AM" src="https://user-images.githubusercontent.com/71772438/94021496-afc4c580-fd79-11ea-89e7-9cd3928f2263.png">
<img width="1885" alt="Screen Shot 2020-09-23 at 8 45 08 AM" src="https://user-images.githubusercontent.com/71772438/94021520-b5221000-fd79-11ea-96ca-c41865fc4c01.png">

**Comment by jp-pollard** [comment]
I think the user is expecting to land somewhere like here: 
https://cloud.ibm.com/docs/vpc?topic=cloud-infrastructure-sysdig-monitoring-metrics


or listed separately as: 
`VSI for Classic` - https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-classic-sysdig-metrics
`VSI for VPC` - https://cloud.ibm.com/docs/cloud-infrastructure?topic=cloud-infrastructure-vpc-sysdig-metrics

**Comment by lopezdsr** [comment]
Thank you for reporting the issue. It has been fixed.
