### ISSUE TITLE
VPC Section is incomplete/inaccurate 

### ISSUE THREAD

**Issue by jp-pollard** [ibm-cloud-docs/Monitoring-with-Sysdig#16]
The VPC section: https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-cloud_services#vpc_infrastructure

1. We only show details for `Gen 1`, where's the info for `Gen 2`?
2. Also, `Gen 1` is scheduled for End of Life. It is currently under an allow list, so if users don't have pre-existing resources in Gen 1, they won't even be able to access Gen 1.

**Comment by lopezdsr** [comment]
Thank you for the feedback - I have fixed the section and included VPC gen 2.
