### ISSUE TITLE
Link needs update

### ISSUE THREAD

**Issue by jmilst** [ibm-cloud-docs/Monitoring-with-Sysdig#17]
Please update the _Metrics collected by IBM Cloud™ Virtual Servers_ link at line 41 to direct to the new location: /docs/cloud-infrastructure?topic=cloud-infrastructure-classic-sysdig-metrics

Thanks!

Per https://github.ibm.com/Bluemix/Documentation-content/issues/15941

**Comment by lopezdsr** [comment]
done
