### ISSUE TITLE
Is this correct ....IBM Cloud Monitoring with Sysdig agent for Kubernetes, GKE, and OpenShift?

### ISSUE THREAD

**Issue by kbroussard** [ibm-cloud-docs/Monitoring-with-Sysdig#6]
https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Sysdig-about#overview_sysdig_agent

"IBM Cloud Monitoring with Sysdig agent for Kubernetes, GKE, and OpenShift."
Did we really mean to list GKE or did we mean to say IKS here?  Why would we talk about IBM Cloud Monitoring with Sysdig for a competitor solution?

**Comment by lopezdsr** [comment]
Thanks for the input. I have addressed the comment.
