### ISSUE TITLE
please update the doc 

### ISSUE THREAD

**Issue by dongwangdw** [ibm-cloud-docs/Monitoring-with-Sysdig#8]
when I run this command `ibmcloud ks cluster config --cluster <cluster_name_or_ID>` from https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-kubernetes_cluster

there is an error: `'ks' is not a registered command. See 'ibmcloud help'`

I did not find the replacement from help. I think this command line should updated.

**Comment by lopezdsr** [comment]
`ks` is an option

<img width="629" alt="image" src="https://user-images.githubusercontent.com/5286056/96715784-fec34200-139b-11eb-8ee3-718f8794e914.png">
 The information is correct.
