### ISSUE TITLE
AVT2: The background of code snippet is too light which causes the contrast violation

### ISSUE THREAD

**Issue by xiepingp** [ibm-cloud-docs/Monitoring-with-Sysdig#9]
===== ENVIRONMENT =====
IBM CI 162 Checkpoint Violation: Checkpoint 1.4.3 Contrast (Minimum)
IBM Guidance: https://www.ibm.com/able/guidelines/ci162/contrast.html
Test Tool Type: Manually Check

===== STEPS TO REPRODUCE =====
Go to https://cloud.ibm.com/docs/Monitoring-with-Sysdig?topic=Monitoring-with-Sysdig-baremetal_linux, check the page with WCAG - Color contrast checker tool.

===== DEFECT DESCRIPTION =====
The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, with a 3:1 ratio for large-scale text. (Level AA)

![Contrast - Sysdig - 01](https://user-images.githubusercontent.com/63960906/88282800-cc626400-cd1c-11ea-96cc-849f1ba33ecf.png)

===== EXPECTED RESULT =====
The intent of this Success Criterion is to provide enough contrast between text and its background so that it can be read by people with moderately low vision (who do not use contrast-enhancing assistive technology).
https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum

**Comment by xiepingp** [comment]
@LOPEZDSR, would you please take a look at the issue? Thank you!

**Comment by sethmccombs** [comment]
I don't have access to how IBM renders these docs, but the issue lies around line 74-97 - something in the syntax is causing lines 74-84 and 91-97 to not render properly. The show in the preview on github, but when converted to the docs engine and posted, something is lost

**Comment by xiepingp** [comment]
Hi @sethmccombs, is it possible to fix the problem?

**Comment by sethmccombs** [comment]
@xiepingp iwould assume so, but I'm not sure how all this is generated on the back end as I'm not an IBM employee, I'm on the Sysdig side of things, do you know what web engine (hugo, etc) is used to generate these?

**Comment by xiepingp** [comment]
@lopezdsr, could you please help answer @sethmccombs's question?

**Comment by vanadiscrawford** [comment]
@xiepingp I have resolved the issues with this topic - including the unreadable text as well as the missing steps.  Please verify and close if you confirm the issue is resolved.  Thanks!

**Comment by xiepingp** [comment]
Retest the issue, all looks good:
![9 - fixed](https://user-images.githubusercontent.com/63960906/98194738-04ec1d80-1f5b-11eb-8fd7-f254c98afd4c.png)
Closing it now.
